name: Track Release Downloads

on:
  schedule:
    - cron: '0 0 * * *' # This runs the action daily at midnight UTC

jobs:
  download-tracker:
    runs-on: ubuntu-latest

    steps:
    - name: Get Download Count
      run: |
        download_count=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/KeelNode/afk_pvp_tabbedout_zc/releases/assets/120641248 \
        | jq '.download_count')
        echo "Download count: $download_count"

    - name: Create an Issue (Optional)
      if: ${{ always() }}
      run: |
        if [ "$download_count" -gt 0 ]; then
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"title\":\"Download Count Update\",\"body\":\"Download count: $download_count\"}" \
          https://api.github.com/repos/KeelNode/afk_pvp_tabbedout_zc/issues
        fi
